dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.0
  google_maps_flutter: ^2.5.0
  flutter_barcode_scanner: ^2.0.0
  provider: ^6.1.0

flutter:
  assets:
    - assets/logo.png